version: '3'
services:
  web:
    build: .
    container_name: 'node-test'
    volumes:
      - .:/app
    ports:
      - 4545:8080
    working_dir: /app
    command: >
      bash -c 'npm i && npm run dev'
